//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osanebi.WebBlazor.LocalizationResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osanebi.WebBlazor.LocalizationResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btn_register {
            get {
                return ResourceManager.GetString("btn-register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btn_reset {
            get {
                return ResourceManager.GetString("btn-reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string gender_female {
            get {
                return ResourceManager.GetString("gender-female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string gender_male {
            get {
                return ResourceManager.GetString("gender-male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string gender_other {
            get {
                return ResourceManager.GetString("gender-other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string input_confirm_password {
            get {
                return ResourceManager.GetString("input-confirm-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string input_dob {
            get {
                return ResourceManager.GetString("input-dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string input_email {
            get {
                return ResourceManager.GetString("input-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string input_firstname {
            get {
                return ResourceManager.GetString("input-firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string input_lastname {
            get {
                return ResourceManager.GetString("input-lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string input_password {
            get {
                return ResourceManager.GetString("input-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string label_errors {
            get {
                return ResourceManager.GetString("label-errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string message_confirm_password_match {
            get {
                return ResourceManager.GetString("message-confirm-password-match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required!.
        /// </summary>
        public static string message_confirm_password_required {
            get {
                return ResourceManager.GetString("message-confirm-password-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string message_email_exists {
            get {
                return ResourceManager.GetString("message-email-exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not correct.
        /// </summary>
        public static string message_email_format {
            get {
                return ResourceManager.GetString("message-email-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required!.
        /// </summary>
        public static string message_email_required {
            get {
                return ResourceManager.GetString("message-email-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required!.
        /// </summary>
        public static string message_firstname_required {
            get {
                return ResourceManager.GetString("message-firstname-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Attempt..
        /// </summary>
        public static string message_invalid_login {
            get {
                return ResourceManager.GetString("message-invalid-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Data..
        /// </summary>
        public static string message_invalid_user_data {
            get {
                return ResourceManager.GetString("message-invalid-user-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required!.
        /// </summary>
        public static string message_lastname_required {
            get {
                return ResourceManager.GetString("message-lastname-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is not allowed.
        /// </summary>
        public static string message_login_not_allowed {
            get {
                return ResourceManager.GetString("message-login-not-allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string message_password_required {
            get {
                return ResourceManager.GetString("message-password-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters.
        /// </summary>
        public static string message_password_validation {
            get {
                return ResourceManager.GetString("message-password-validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too weak!.
        /// </summary>
        public static string message_password_weak {
            get {
                return ResourceManager.GetString("message-password-weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Authentication Required.
        /// </summary>
        public static string message_two_factor_required {
            get {
                return ResourceManager.GetString("message-two-factor-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        public static string message_unknown_error {
            get {
                return ResourceManager.GetString("message-unknown-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Locked out.
        /// </summary>
        public static string message_user_locked_out {
            get {
                return ResourceManager.GetString("message-user-locked-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Welcome to Osanebi.
        /// </summary>
        public static string message_welcome {
            get {
                return ResourceManager.GetString("message-welcome", resourceCulture);
            }
        }
    }
}
